
# H2 DB - path
spring:
  h2:
    console:
      enabled: true
      path: /payment/dev/h2
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.generate_statistics: true
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:h2:file:~/test
    username: pmtdev
    password: pmtdev
    driver-class-name: org.h2.Driver